name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: bash ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
