env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Java_CI
on: push
jobs: 
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .
  Test:
    needs: [Clone-down]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps: 
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Build:
    needs: [Clone-down]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps: 
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: build-app
        run: bash ci/build-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-image:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: set-git-commit as environment
        run: export GIT_COMMIT="GA-$GITHUB_SHA"
      - run: bash ci/build-docker.sh && bash ci/push-docker.sh
  Component-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
      - run: bash ci/component-test.sh
        

